---
- name: update apt
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: install deps
  apt: >
    pkg={{item}}
    state=installed
  with_items:
    - unzip

- name: create consul-template directory structure
  file: >
    state=directory
    path={{ item }}
  with_items:
    - "{{ consul_template_home }}"
    - "{{ consul_template_home }}/bin"
    - "{{ consul_template_home }}/config"
    - "{{ consul_template_home }}/templates"

- name: download consul-template binary
  get_url:
    url: "{{ consul_template_download_url }}"
    dest: "/tmp"
  delegate_to: localhost

- name: unzip the downloaded package
  unarchive:
    src: "/tmp/{{ consul_template_archive_file }}"
    dest: "/tmp"
    creates: "/tmp/{{ consul_template_release }}/{{ consul_template_binary }}"
  delegate_to: localhost

- name: copy consul-template binary into place
  copy:
    src: "/tmp/{{ consul_template_release }}/{{ consul_template_binary }}"
    dest: "{{ consul_template_home }}/bin/{{ consul_template_binary }}"
    owner: "root"
    group: "root"
    mode: "0755"

- name: copy consul-template systemd service configuration
  template: >
    src=consul-template.service.systemd.j2
    dest=/etc/systemd/system/consul-template.service
    mode=0755
  when: consul_template_use_systemd

- name: copy consul-template upstart service configuration
  template: >
    src=consul-template.service.upstart.j2
    dest=/etc/init/consul-template.conf
    mode=0755
  when: consul_template_use_upstart

- name: add consul-template to path through profile.d
  template: >
    src=consul-template.sh.j2
    dest=/etc/profile.d/consul-template.sh
    owner=root
    group=root
    mode=0755

- name: consul-template config file
  template: >
    src={{ consul_template_config_file_template }}
    dest={{ consul_template_home }}/config/{{ consul_template_config_file }}
    mode=0755
